[package]
name = 'rustycogs'
version = '0.1.0'
edition = '2021'

[lib]
crate-type = [ 'staticlib' ]
name = 'rustycogs'

[dependencies]
extendr-api = '*'
async-tiff = '*'
object_store = "0.12"
tokio = { version = "1.43", features = ["rt-multi-thread"] }
