# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustycogs_wrappers", use_symbols = TRUE, package_name = "rustycogs")

#' @usage NULL
#' @useDynLib rustycogs, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
#' @export
rusty <- function(file) .Call(wrap__rusty, file)


# nolint end
