# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_rustycogs_wrappers", use_symbols = TRUE, package_name = "rustycogs")

#' @usage NULL
#' @useDynLib rustycogs, .registration = TRUE
NULL

#' Extract tile byte-range references from TIFF/COG files.
#'
#' @param paths Character vector of file paths or URLs
#'   (s3://, gs://, az://, http://, https://, or local paths).
#' @param region Optional AWS region string (e.g. "us-west-2").
#' @param anon Logical, use anonymous/unsigned requests. Default FALSE.
#' @return A data.frame with columns: path, ifd, tile_col, tile_row,
#'   offset, length, image_w, image_h, tile_w, tile_h, dtype,
#'   compression, bits_per_sample, samples_per_pixel, crs_epsg.
#' @export
tiff_refs <- function(paths, region = "", anon = TRUE) .Call(wrap__tiff_refs, paths, region, anon)


# nolint end
