# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_rustycogs_wrappers", use_symbols = TRUE, package_name = "rustycogs")

#' @usage NULL
#' @useDynLib rustycogs, .registration = TRUE
NULL

#' Return string `"Hello world!"` to R.
rusty_rs <- function(file, dir, tile_i, tile_j) .Call(wrap__rusty_rs, file, dir, tile_i, tile_j)


